## 1 application de l'algorithme de gene cas reel (croisement :"technique de wright"  mutation:"mutation Muchalwicz" Selection = "Davi" )

 ### 1.1 importation du jeux de donnees from kaggle voir le lien ci dessous . 
 <a>https://www.kaggle.com/datasets/yasserh/advertising-sales-dataset/data</a>


 ### 1.1 importation du jeux de donnees from kaggle voir le lien ci dessous . 
 <a>https://www.kaggle.com/datasets/yasserh/advertising-sales-dataset/data</a>


In [27]:
import numpy as np
import pandas as pd
DataSet = pd.read_csv(r"C:\Users\PC\Downloads\Advertising Budget and Sales.csv")
DataSet = DataSet.drop(columns='Unnamed: 0')

In [28]:
DataSet.describe()

TV Ad Budget ($)  Radio Ad Budget ($)  Newspaper Ad Budget ($)  \
count        200.000000           200.000000               200.000000   
mean         147.042500            23.264000                30.554000   
std           85.854236            14.846809                21.778621   
min            0.700000             0.000000                 0.300000   
25%           74.375000             9.975000                12.750000   
50%          149.750000            22.900000                25.750000   
75%          218.825000            36.525000                45.100000   
max          296.400000            49.600000               114.000000   

        Sales ($)  
count  200.000000  
mean    14.022500  
std      5.217457  
min      1.600000  
25%     10.375000  
50%     12.900000  
75%     17.400000  
max     27.000000

In [29]:
DataSet.head()

TV Ad Budget ($)  Radio Ad Budget ($)  Newspaper Ad Budget ($)  Sales ($)
0             230.1                 37.8                     69.2       22.1
1              44.5                 39.3                     45.1       10.4
2              17.2                 45.9                     69.3        9.3
3             151.5                 41.3                     58.5       18.5
4             180.8                 10.8                     58.4       12.9

In [35]:
X = DataSet.iloc[:, :3].values  # 3 colonnes indépendantes
y = DataSet.iloc[:, 3].values   # colonne dépendante
X

array([[230.1,  37.8,  69.2],
       [ 44.5,  39.3,  45.1],
       [ 17.2,  45.9,  69.3],
       [151.5,  41.3,  58.5],
       [180.8,  10.8,  58.4],
       [  8.7,  48.9,  75. ],
       [ 57.5,  32.8,  23.5],
       [120.2,  19.6,  11.6],
       [  8.6,   2.1,   1. ],
       [199.8,   2.6,  21.2],
       [ 66.1,   5.8,  24.2],
       [214.7,  24. ,   4. ],
       [ 23.8,  35.1,  65.9],
       [ 97.5,   7.6,   7.2],
       [204.1,  32.9,  46. ],
       [195.4,  47.7,  52.9],
       [ 67.8,  36.6, 114. ],
       [281.4,  39.6,  55.8],
       [ 69.2,  20.5,  18.3],
       [147.3,  23.9,  19.1],
       [218.4,  27.7,  53.4],
       [237.4,   5.1,  23.5],
       [ 13.2,  15.9,  49.6],
       [228.3,  16.9,  26.2],
       [ 62.3,  12.6,  18.3],
       [262.9,   3.5,  19.5],
       [142.9,  29.3,  12.6],
       [240.1,  16.7,  22.9],
       [248.8,  27.1,  22.9],
       [ 70.6,  16. ,  40.8],
       [292.9,  28.3,  43.2],
       [112.9,  17.4,  38.6],
       [ 97.2,   1.5,  30. ],
       [26

#### Etape1 : Initialisation de la population (les individus represente un vecteur aleatoire entre 10 et -10 qui est la pente de la droite de regression w)

In [31]:
borne_max=10
borne_min=-10
taille_population=30
nb_variables=3 #Puisque ona un vecteur de 3 element et en traite la regression multiple avec trois variable 
population = np.random.uniform(borne_min, borne_max, (taille_population, nb_variables))
population 

array([[-7.58728258, -0.78442464, -5.87332563],
       [-2.71460278,  0.06834542,  3.80789657],
       [-9.2137572 ,  5.98820798,  2.55800779],
       [-8.36481936,  7.47157248,  8.41744801],
       [-8.7784408 , -4.46244704,  6.1240256 ],
       [ 4.96519381, -6.30957961, -5.81301353],
       [-2.59055794, -0.3095403 ,  2.36509543],
       [-2.62172721, -0.74930568,  4.94941876],
       [-9.26633594, -4.95126111,  4.26699172],
       [ 7.90413675,  0.23354884,  0.64226971],
       [-7.85655977, -1.05175266,  0.65234533],
       [-5.15058993, -4.61513538, -2.45431674],
       [-9.59857604, -3.55841669, -5.77103986],
       [-3.45005296, -7.60475736,  7.81054561],
       [ 1.87184907,  3.58204638,  5.78342477],
       [-0.03115602, -8.26159424,  0.74213084],
       [ 1.73682236,  4.90878948, -1.36680908],
       [-7.44839394, -4.32448188, -2.73835407],
       [ 2.91834483,  1.41556609, -2.87806548],
       [ 9.73030498,  2.11549639, -5.25546417],
       [-7.96435055, -6.94281722, -5.080

### Etape 2 : Selection des individus pour faire le croisement en utilisant la methode Davis 

#### Etape 2 : 1 implimentation de la fonction fitness 

In [38]:
def fitness_population(population, X, y,N_individu):

    
    fitness = np.zeros(N_individu)

    for i in range(N_individu):
        W = population[i]
        y_pred = X @ W  # produit scalaire (prédiction)
        erreur = np.mean(np.abs(y_pred - y))  # MAE
        fitness[i] = -erreur  # fitness = -erreur en prend l'inverse pour  On transforme le problème de minimisation en problème de maximisation 
    
    return fitness

#### Etape 2 : 2 implimentation de la fonction selection par davis

In [39]:
def selection_davis(population, X, y, alpha=1.3, nb_selection=None):

    N = population.shape[0]
    if nb_selection is None:
        nb_selection = N

    # Étape 1 : calculer la fitness de chaque individu
    fitness = fitness_population(population, X, y,30)

    # Étape 2 : trier les individus par fitness décroissante
    indices_tries = np.argsort(fitness)[::-1]
    population_triee = population[indices_tries]

    # Étape 3 : calcul des poids relatifs Rw_i = (n - i)^alpha
    rangs = np.arange(N)
    Rw = (N - rangs) ** alpha

    # Étape 4 : probabilités de reproduction
    Pr = Rw / np.sum(Rw)

    # Étape 5 : sélection pondérée
    indices_selectionnes = np.random.choice(N, size=nb_selection, p=Pr)
    population_selectionnee = population_triee[indices_selectionnes]

    return population_selectionnee

# Sélection selon Davis
population_sel = selection_davis(population, X, y, alpha=1.3)
print("Nouvelle population sélectionnée :\n", population_sel)

Nouvelle population sélectionnée :
 [[-0.03115602 -8.26159424  0.74213084]
 [ 4.96519381 -6.30957961 -5.81301353]
 [ 1.73682236  4.90878948 -1.36680908]
 [-3.45005296 -7.60475736  7.81054561]
 [-2.62172721 -0.74930568  4.94941876]
 [ 2.91834483  1.41556609 -2.87806548]
 [-1.49127123  0.15220757 -5.15180535]
 [ 1.13525786  1.43225379 -4.40041813]
 [ 1.73682236  4.90878948 -1.36680908]
 [-0.03115602 -8.26159424  0.74213084]
 [ 1.13525786  1.43225379 -4.40041813]
 [-7.58728258 -0.78442464 -5.87332563]
 [ 1.73682236  4.90878948 -1.36680908]
 [-5.15058993 -4.61513538 -2.45431674]
 [ 0.49022779 -1.79206346  9.64757234]
 [ 1.87184907  3.58204638  5.78342477]
 [-8.36481936  7.47157248  8.41744801]
 [-3.45005296 -7.60475736  7.81054561]
 [ 2.91834483  1.41556609 -2.87806548]
 [-2.59055794 -0.3095403   2.36509543]
 [-2.71460278  0.06834542  3.80789657]
 [-7.85655977 -1.05175266  0.65234533]
 [-7.75922196 -2.04288802  9.38940867]
 [-6.78637253 -6.26865952 -4.29809663]
 [-0.03115602 -8.26159424  0

### Etape 3 : Croisement des individus selectionner par la technique de wright 

In [40]:

def croisement_wright(population, pc=0.8):

    N, d = population.shape
    nouvelle_population = []

    # Mélanger la population pour former des paires aléatoires
    indices = np.random.permutation(N)

    for i in range(0, N - 1, 2):
        parent1 = population[indices[i]]
        parent2 = population[indices[i+1]]

        if np.random.rand() < pc:  # verification de la condition de croisement 
            # Croisement de Wright
            beta = np.random.rand()
            enfant1 = beta * parent1 + (1 - beta) * parent2
            enfant2 = beta * parent2 + (1 - beta) * parent1
        else:
            # Pas de croisement : on garde les parents
            enfant1 = parent1.copy()
            enfant2 = parent2.copy()

        nouvelle_population.append(enfant1)
        nouvelle_population.append(enfant2)

    # Si population impaire, ajouter le dernier non croisé
    if N % 2 != 0:
        nouvelle_population.append(population[indices[-1]])

    return np.array(nouvelle_population)
    
# Appliquer le croisement sur la population sélectionnée
population_apres_croisement = croisement_wright(population_sel, pc=0.8)
population_apres_croisement

array([[-4.62344037e+00,  3.55755912e+00,  8.93719243e+00],
       [-3.25115120e+00,  2.12194991e+00,  9.12782792e+00],
       [-4.62919421e+00, -3.71160277e+00, -3.28349277e+00],
       [-2.98924439e+00, -5.33441611e+00, -1.84770202e+00],
       [-7.41489015e+00, -1.92741393e+00,  8.92145515e+00],
       [-2.93488975e+00, -4.25014383e-01,  2.83304894e+00],
       [ 7.02738981e-03, -2.70808099e+00,  2.00824045e+00],
       [-5.38735520e-01, -3.48111028e+00,  2.92423968e+00],
       [-6.64359196e+00,  4.04589492e+00, -7.93973011e-03],
       [-4.06143647e+00,  2.09452063e+00, -2.58585783e+00],
       [ 2.30829981e+00, -9.38933468e-01, -4.83307123e+00],
       [ 3.79215186e+00, -3.93839236e+00, -5.38036043e+00],
       [ 1.64087966e+00,  2.14457324e+00,  5.17155847e+00],
       [ 1.99813390e-01, -6.82412110e+00,  1.35399714e+00],
       [-4.13982576e-01,  4.51169281e+00,  1.20677404e+00],
       [-4.43144332e+00,  3.76996107e+00,  6.01393667e+00],
       [-3.45775113e+00, -7.60167447e+00

#### Etape 4 : Mutation en utilisant la Mutation de Michalewicz pour assurer la diversity de la ppopulation 

In [41]:
def mutation_michalewicz(population, t, T, xmin, xmax, pm=0.1, b=3):

    N, d = population.shape
    nouvelle_population = population.copy()

    for i in range(N):
        for j in range(d):
            if np.random.rand() < pm:
                r = np.random.rand()
                direction = np.random.choice(["pile", "face"])
                y = xmax[j] - population[i, j] if direction == "pile" else population[i, j] - xmin[j]
                delta = r * y * ((1 - t / T) ** b)
                if direction == "pile":
                    nouvelle_population[i, j] += delta
                else:
                    nouvelle_population[i, j] -= delta

                # Clamping to bounds
                nouvelle_population[i, j] = np.clip(nouvelle_population[i, j], xmin[j], xmax[j])

    return nouvelle_population
# Supposons que nous sommes à la génération 5/50
population_mutée = mutation_michalewicz(population_apres_croisement,
                                         t=5, T=100,
                                         xmin=np.array([-10, -10, -10]),
                                         xmax=np.array([10, 10, 10]),
                                         pm=0.1, b=3)
population_mutée

array([[-4.62344037e+00,  3.55755912e+00,  8.93719243e+00],
       [-3.25115120e+00,  2.12194991e+00,  9.12782792e+00],
       [-7.38489994e+00, -3.71160277e+00, -3.28349277e+00],
       [-2.98924439e+00, -5.33441611e+00, -1.84770202e+00],
       [-7.41489015e+00, -1.92741393e+00,  8.92145515e+00],
       [-2.93488975e+00, -4.25014383e-01,  2.83304894e+00],
       [ 7.02738981e-03, -2.70808099e+00, -6.97076808e+00],
       [-5.38735520e-01, -3.48111028e+00,  2.92423968e+00],
       [ 2.65128764e+00,  4.04589492e+00, -7.93973011e-03],
       [-4.06143647e+00,  2.09452063e+00, -2.58585783e+00],
       [ 2.30829981e+00, -9.38933468e-01, -4.83307123e+00],
       [ 3.79215186e+00, -3.93839236e+00, -5.38036043e+00],
       [ 1.64087966e+00,  2.14457324e+00,  5.17155847e+00],
       [ 1.99813390e-01, -6.82412110e+00, -1.90902509e+00],
       [-4.13982576e-01,  4.51169281e+00,  1.20677404e+00],
       [-4.43144332e+00,  3.76996107e+00,  6.01393667e+00],
       [-3.45775113e+00, -7.60167447e+00

#### Etape 5 : Applique toutes les étapes de l’algorithme (initialisation → sélection → croisement → mutation)

In [45]:
def algorithme_genetique_reel(X, y, population,n_generations=100, population_size=30, pc=0.8, pm=0.1, alpha=1.3, b=3):
    
    N, d = X.shape

    # Définir les bornes (à adapter si besoin)
    xmin = np.full(d, -10)
    xmax = np.full(d, 10)

    for t in range(n_generations):
        # Étape 2 : Sélection (Davis)
        population_sel = selection_davis(population, X, y, alpha=alpha)

        # Étape 3 : Croisement (Wright)
        population_cross = croisement_wright(population_sel, pc=pc)

        # Étape 4 : Mutation (Michalewicz)
        population = mutation_michalewicz(population_cross, t, n_generations, xmin, xmax, pm=pm, b=b)

        # Évaluation
        fitness = fitness_population(population, X, y,30)
        best_index = np.argmax(fitness)
        best_fitness = fitness[best_index]
        best_individu = population[best_index]

        print(f"Génération {t+1}/{n_generations} : meilleure fitness = {best_fitness:.6f}, W = {best_individu}")

    # Résultat final
    print("\n✅ Meilleure solution approchée trouvée :")
    print(f"W = {best_individu}")
    print(f"Fitness = {best_fitness:.6f}")


algorithme_genetique_reel(X, y,population)


Génération 1/100 : meilleure fitness = -200.350991, W = [ 1.84179184  1.42564142 -3.79719804]
Génération 2/100 : meilleure fitness = -48.026335, W = [ 0.51724666  0.90710686 -1.95568361]
Génération 3/100 : meilleure fitness = -48.026335, W = [ 0.51724666  0.90710686 -1.95568361]
Génération 4/100 : meilleure fitness = -41.553817, W = [-0.34861082  2.47342274 -0.4222883 ]
Génération 5/100 : meilleure fitness = -38.478664, W = [ 0.30974377  1.03651988 -2.1162566 ]
Génération 6/100 : meilleure fitness = -23.655125, W = [ 0.20172879 -0.20492201 -0.90943963]
Génération 7/100 : meilleure fitness = -11.213937, W = [ 0.05980321 -0.22694769  0.5929761 ]
Génération 8/100 : meilleure fitness = -11.213937, W = [ 0.05980321 -0.22694769  0.5929761 ]
Génération 9/100 : meilleure fitness = -7.293024, W = [ 0.05857758 -0.25622052  0.40548015]
Génération 10/100 : meilleure fitness = -6.220228, W = [ 0.0646713  -0.26414306  0.27100851]
Génération 11/100 : meilleure fitness = -5.797201, W = [ 0.07215273 -0

## 2 application de l'algorithme de gene cas reel Methode simple comme l'Exercice 2 Examen 

In [48]:
import numpy as np

# ---- Fonction d'évaluation (fitness) : erreur absolue ----
def fitness(w, x, t):
    y_pred = np.dot(x, w)
    return np.abs(y_pred - t).sum()  # Erreur absolue totale

# ---- Initialisation de la population ----
def initialiser_population(taille_pop, dimension, borne_min=-5, borne_max=5):
    return np.random.randint(borne_min, borne_max + 1, size=(taille_pop, dimension))

# ---- Sélection : garder les meilleurs individus (plus faible erreur) ----
def selection(population, x, t, nb_selection):
    scores = np.array([fitness(ind, x, t) for ind in population])
    indices = np.argsort(scores)
    return population[indices[:nb_selection]]

# ---- Croisement par pivot ----
def croisement(parent1, parent2):
    point_pivot = np.random.randint(1, len(parent1))
    enfant1 = np.concatenate((parent1[:point_pivot], parent2[point_pivot:]))
    enfant2 = np.concatenate((parent2[:point_pivot], parent1[point_pivot:]))
    return enfant1, enfant2

# ---- Mutation aléatoire ----
def mutation(individu, prob_mutation=0.1, borne_min=-5, borne_max=5):
    for i in range(len(individu)):
        if np.random.rand() < prob_mutation:
            individu[i] = np.random.randint(borne_min, borne_max + 1)
    return individu

# ---- Algorithme génétique principal ----
def algorithme_genetique(x, t, generations=20, taille_pop=10, nb_selection=4, prob_mutation=0.1):
    dimension = x.shape[1]
    population = initialiser_population(taille_pop, dimension)

    for gen in range(generations):
        print(f"\n🧬 Génération {gen + 1}")
        
        # Évaluer la population
        scores = [fitness(ind, x, t) for ind in population]
        for i, (ind, score) in enumerate(zip(population, scores)):
            print(f" Individu {i} : {ind} -> Erreur = {score:.4f}")
        
        # Sélection des meilleurs
        parents = selection(population, x, t, nb_selection)

        # Croisement
        enfants = []
        while len(enfants) < taille_pop - nb_selection:
            p1, p2 = parents[np.random.randint(0, nb_selection)], parents[np.random.randint(0, nb_selection)]
            e1, e2 = croisement(p1, p2)
            enfants.append(e1)
            if len(enfants) < taille_pop - nb_selection:
                enfants.append(e2)

        # Mutation
        enfants = [mutation(ind, prob_mutation) for ind in enfants]

        # Nouvelle population = parents + enfants
        population = np.vstack((parents, enfants))

    # Évaluer la population finale
    scores = [fitness(ind, x, t) for ind in population]
    meilleur_indice = np.argmin(scores)
    meilleur_individu = population[meilleur_indice]
    print(f"\n✅ Meilleure solution trouvée : {meilleur_individu}")
    print(f"   Erreur totale : {scores[meilleur_indice]:.4f}")
    return meilleur_individu
# Exemple fictif
x = np.array([[4, -2, 7, 7, 11, 1]])
t = np.array([64.2])

# Appel de l'algorithme
w_opt = algorithme_genetique(x, t, generations=10)


🧬 Génération 1
 Individu 0 : [ 2 -4 -1 -4 -1  1] -> Erreur = 93.2000
 Individu 1 : [ 0 -1 -2  2  5  2] -> Erreur = 5.2000
 Individu 2 : [-5  4 -4 -3 -5  5] -> Erreur = 191.2000
 Individu 3 : [-3  4  2 -2  1  1] -> Erreur = 72.2000
 Individu 4 : [ 5 -1 -5  4 -2  1] -> Erreur = 70.2000
 Individu 5 : [-1 -4  2 -4  5  2] -> Erreur = 17.2000
 Individu 6 : [ 5 -4  5 -1 -2 -5] -> Erreur = 35.2000
 Individu 7 : [ 2  4 -3 -2 -2 -1] -> Erreur = 122.2000
 Individu 8 : [-3  3 -2  4  5  5] -> Erreur = 8.2000
 Individu 9 : [-2  0  2  1 -2 -2] -> Erreur = 75.2000

🧬 Génération 2
 Individu 0 : [ 0 -1 -2  2  5  2] -> Erreur = 5.2000
 Individu 1 : [-3  3 -2  4  5  5] -> Erreur = 8.2000
 Individu 2 : [-1 -4  2 -4  5  2] -> Erreur = 17.2000
 Individu 3 : [ 5 -4  5 -1 -2 -5] -> Erreur = 35.2000
 Individu 4 : [ 0 -1 -2  2  5  5] -> Erreur = 2.2000
 Individu 5 : [-3  3 -2  4  5  2] -> Erreur = 11.2000
 Individu 6 : [ 5 -5  5  4 -2  0] -> Erreur = 6.8000
 Individu 7 : [ 0 -1 -2 -2  5 -5] -> Erreur = 40.2000


#### Conclusion 

Méthode 1 (Wright + Michalewicz + Davi) est clairement plus robuste, surtout pour les problèmes réels à variables continues. La descente de fitness montre une bonne exploitation après une phase d’exploration. La stagnation est naturelle vers la fin (proche d’un optimum local ou global).

Méthode 2 montre que l’algorithme génétique est très efficace même en version simple, à condition que :
Le codage soit adapté.